# This is a basic workflow to help you get started with Actions

name: Trigger CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo "ref = " ${{ github.event.client_payload.ref }}
      - run: echo "sha = " ${{ github.event.client_payload.sha }}
      - run: echo "IMAGE_TAG value = " ${{ github.event.client_payload.IMAGE_TAG }}
      - run: |
              echo "git version = " git --version
              pwd
              ls -lrt
              cat deployment-hello-hapi.yaml
              sed -i 's/hello-hapi:.*/hello-hapi:'"$github.event.client_payload.IMAGE_TAG"'/g' deployment-hello-hapi.yaml
              grep hello-hapi:.* deployment-hello-hapi.yaml
              #git config --global user.name “chloongloong”
              #git config --global user.email "loongch@yahoo.com.sg"
              #git add deployment-hello-hapi.yaml
              #git commit -m "Updated deployment Manifest to image ver $github.event.client_payload.IMAGE_TAG"
              #git push
